export enum BusinessIndustryRoles {
    // C-Suite and Executive Roles
    CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
    CHIEF_OPERATING_OFFICER = 'CHIEF_OPERATING_OFFICER',
    CHIEF_FINANCIAL_OFFICER = 'CHIEF_FINANCIAL_OFFICER',
    CHIEF_MARKETING_OFFICER = 'CHIEF_MARKETING_OFFICER',
    CHIEF_HUMAN_RESOURCES_OFFICER = 'CHIEF_HUMAN_RESOURCES_OFFICER',
    CHIEF_INFORMATION_OFFICER = 'CHIEF_INFORMATION_OFFICER',
    PRESIDENT = 'PRESIDENT',
    VICE_PRESIDENT = 'VICE_PRESIDENT',

    // Management Roles
    GENERAL_MANAGER = 'GENERAL_MANAGER',
    OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    PRODUCT_MANAGER = 'PRODUCT_MANAGER',
    ACCOUNT_MANAGER = 'ACCOUNT_MANAGER',

    // Finance and Accounting
    FINANCIAL_CONTROLLER = 'FINANCIAL_CONTROLLER',
    ACCOUNTANT = 'ACCOUNTANT',
    FINANCIAL_ANALYST = 'FINANCIAL_ANALYST',
    AUDITOR = 'AUDITOR',

    // Sales and Marketing
    SALES_DIRECTOR = 'SALES_DIRECTOR',
    SALES_REPRESENTATIVE = 'SALES_REPRESENTATIVE',
    MARKETING_MANAGER = 'MARKETING_MANAGER',
    DIGITAL_MARKETING_SPECIALIST = 'DIGITAL_MARKETING_SPECIALIST',
    PUBLIC_RELATIONS_MANAGER = 'PUBLIC_RELATIONS_MANAGER',

    // Human Resources
    HR_MANAGER = 'HR_MANAGER',
    RECRUITER = 'RECRUITER',
    TRAINING_AND_DEVELOPMENT_SPECIALIST = 'TRAINING_AND_DEVELOPMENT_SPECIALIST',
    COMPENSATION_AND_BENEFITS_ANALYST = 'COMPENSATION_AND_BENEFITS_ANALYST',

    // Operations and Logistics
    SUPPLY_CHAIN_MANAGER = 'SUPPLY_CHAIN_MANAGER',
    LOGISTICS_COORDINATOR = 'LOGISTICS_COORDINATOR',
    PROCUREMENT_SPECIALIST = 'PROCUREMENT_SPECIALIST',
    QUALITY_ASSURANCE_MANAGER = 'QUALITY_ASSURANCE_MANAGER',

    // Information Technology
    IT_MANAGER = 'IT_MANAGER',
    SYSTEMS_ANALYST = 'SYSTEMS_ANALYST',
    BUSINESS_INTELLIGENCE_ANALYST = 'BUSINESS_INTELLIGENCE_ANALYST',

    // Legal
    GENERAL_COUNSEL = 'GENERAL_COUNSEL',
    COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',

    // Customer Service
    CUSTOMER_SERVICE_MANAGER = 'CUSTOMER_SERVICE_MANAGER',
    CUSTOMER_SUPPORT_REPRESENTATIVE = 'CUSTOMER_SUPPORT_REPRESENTATIVE',

    // Research and Development
    RESEARCH_DIRECTOR = 'RESEARCH_DIRECTOR',
    PRODUCT_DEVELOPMENT_MANAGER = 'PRODUCT_DEVELOPMENT_MANAGER',

    // Administrative
    EXECUTIVE_ASSISTANT = 'EXECUTIVE_ASSISTANT',
    OFFICE_MANAGER = 'OFFICE_MANAGER',

    // Consulting
    MANAGEMENT_CONSULTANT = 'MANAGEMENT_CONSULTANT',
    BUSINESS_ANALYST = 'BUSINESS_ANALYST',

    // Other
    ENTREPRENEUR = 'ENTREPRENEUR',
    BUSINESS_DEVELOPMENT_MANAGER = 'BUSINESS_DEVELOPMENT_MANAGER',
    RISK_MANAGER = 'RISK_MANAGER',
    OWNER = "OWNER",
    MANAGER = "MANAGER",
    EMPLOYEE = "EMPLOYEE",
    VIEWER = "VIEWER",
    DEFAULT_ROLE = "DEFAULT_ROLE"
}