// src/constants/AccessKey/Roles/family.ts

export enum FamilyRoles {
    HEAD_OF_HOUSEHOLD = 'HEAD_OF_HOUSEHOLD',
    // Nuclear Family
    MOTHER = 'MOTHER',
    FATHER = 'FATHER',
    CHILD = 'CHILD',
    SON = 'SON',
    DAUGHTER = 'DAUGHTER',
    SIBLING = 'SIBLING',
    BROTHER = 'BROTHER',
    SISTER = 'SISTER',

    // Extended Family
    GRANDPARENT = 'GRANDPARENT',
    GRANDMOTHER = 'GRANDMOTHER',
    GRANDFATHER = 'GRANDFATHER',
    GRANDCHILD = 'GRANDCHILD',
    GRANDSON = 'GRANDSON',
    GRANDDAUGHTER = 'GRANDDAUGHTER',
    AUNT = 'AUNT',
    UNCLE = 'UNCLE',
    NIECE = 'NIECE',
    NEPHEW = 'NEPHEW',
    COUSIN = 'COUSIN',

    // In-Laws
    PARENT_IN_LAW = 'PARENT_IN_LAW',
    MOTHER_IN_LAW = 'MOTHER_IN_LAW',
    FATHER_IN_LAW = 'FATHER_IN_LAW',
    SIBLING_IN_LAW = 'SIBLING_IN_LAW',
    BROTHER_IN_LAW = 'BROTHER_IN_LAW',
    SISTER_IN_LAW = 'SISTER_IN_LAW',

    // Step Family
    STEP_PARENT = 'STEP_PARENT',
    STEP_MOTHER = 'STEP_MOTHER',
    STEP_FATHER = 'STEP_FATHER',
    STEP_CHILD = 'STEP_CHILD',
    STEP_SON = 'STEP_SON',
    STEP_DAUGHTER = 'STEP_DAUGHTER',
    STEP_SIBLING = 'STEP_SIBLING',
    STEP_BROTHER = 'STEP_BROTHER',
    STEP_SISTER = 'STEP_SISTER',

    // Other
    SPOUSE = 'SPOUSE',
    PARTNER = 'PARTNER',
    GUARDIAN = 'GUARDIAN',
    GODPARENT = 'GODPARENT',
    GODCHILD = 'GODCHILD',

    // Family Head Roles
    FAMILY_HEAD = 'FAMILY_HEAD',
    MATRIARCH = 'MATRIARCH',
    PATRIARCH = 'PATRIARCH',

    // Generic
    RELATIVE = 'RELATIVE',
    FAMILY_MEMBER = 'FAMILY_MEMBER'
}