export enum FinanceIndustryRoles {
    // C-Suite and Executive Roles
    CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
    CHIEF_FINANCIAL_OFFICER = 'CHIEF_FINANCIAL_OFFICER',
    CHIEF_OPERATING_OFFICER = 'CHIEF_OPERATING_OFFICER',
    CHIEF_RISK_OFFICER = 'CHIEF_RISK_OFFICER',
    CHIEF_INVESTMENT_OFFICER = 'CHIEF_INVESTMENT_OFFICER',
    PRESIDENT = 'PRESIDENT',
    VICE_PRESIDENT = 'VICE_PRESIDENT',

    // Management Roles
    DIRECTOR = 'DIRECTOR',
    MANAGER = 'MANAGER',
    SUPERVISOR = 'SUPERVISOR',
    TEAM_LEADER = 'TEAM_LEADER',

    // Financial Roles
    FINANCIAL_ANALYST = 'FINANCIAL_ANALYST',
    INVESTMENT_BANKER = 'INVESTMENT_BANKER',
    PORTFOLIO_MANAGER = 'PORTFOLIO_MANAGER',
    TRADER = 'TRADER',
    RISK_ANALYST = 'RISK_ANALYST',
    ACTUARY = 'ACTUARY',

    // Banking Roles
    BANKER = 'BANKER',
    LOAN_OFFICER = 'LOAN_OFFICER',
    CREDIT_ANALYST = 'CREDIT_ANALYST',
    BRANCH_MANAGER = 'BRANCH_MANAGER',
    RELATIONSHIP_MANAGER = 'RELATIONSHIP_MANAGER',

    // Accounting and Audit Roles
    ACCOUNTANT = 'ACCOUNTANT',
    AUDITOR = 'AUDITOR',
    TAX_PROFESSIONAL = 'TAX_PROFESSIONAL',
    CONTROLLER = 'CONTROLLER',
    TREASURER = 'TREASURER',

    // Insurance Roles
    INSURANCE_AGENT = 'INSURANCE_AGENT',
    UNDERWRITER = 'UNDERWRITER',
    CLAIMS_ADJUSTER = 'CLAIMS_ADJUSTER',

    // Stakeholder Roles
    INVESTOR = 'INVESTOR',
    SHAREHOLDER = 'SHAREHOLDER',
    STOCKHOLDER = 'STOCKHOLDER',
    STAKEHOLDER = 'STAKEHOLDER',
    PARTNER = 'PARTNER',

    // Governance Roles
    BOARD_MEMBER = 'BOARD_MEMBER',
    CHAIR = 'CHAIR',
    TRUSTEE = 'TRUSTEE',

    // Regulatory and Compliance Roles
    COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
    REGULATORY_AFFAIRS_SPECIALIST = 'REGULATORY_AFFAIRS_SPECIALIST',

    // Advisory Roles
    FINANCIAL_ADVISOR = 'FINANCIAL_ADVISOR',
    WEALTH_MANAGER = 'WEALTH_MANAGER',
    CONSULTANT = 'CONSULTANT',

    // Fintech Roles
    FINTECH_DEVELOPER = 'FINTECH_DEVELOPER',
    DATA_SCIENTIST = 'DATA_SCIENTIST',
    BLOCKCHAIN_SPECIALIST = 'BLOCKCHAIN_SPECIALIST',

    // Other
    ADMINISTRATOR = 'ADMINISTRATOR',
    ANALYST = 'ANALYST',
    SPECIALIST = 'SPECIALIST',
    ASSOCIATE = 'ASSOCIATE'
}