export enum HealthCareIndustryRoles {
    // C-Suite and Executive Roles
    CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
    CHIEF_MEDICAL_OFFICER = 'CHIEF_MEDICAL_OFFICER',
    CHIEF_NURSING_OFFICER = 'CHIEF_NURSING_OFFICER',
    CHIEF_OPERATING_OFFICER = 'CHIEF_OPERATING_OFFICER',
    HOSPITAL_ADMINISTRATOR = 'HOSPITAL_ADMINISTRATOR',

    // Medical Professionals
    PHYSICIAN = 'PHYSICIAN',
    SURGEON = 'SURGEON',
    NURSE_PRACTITIONER = 'NURSE_PRACTITIONER',
    REGISTERED_NURSE = 'REGISTERED_NURSE',
    PHYSICIAN_ASSISTANT = 'PHYSICIAN_ASSISTANT',
    ANESTHESIOLOGIST = 'ANESTHESIOLOGIST',
    RADIOLOGIST = 'RADIOLOGIST',
    PHARMACIST = 'PHARMACIST',

    // Specialized Medical Roles
    CARDIOLOGIST = 'CARDIOLOGIST',
    NEUROLOGIST = 'NEUROLOGIST',
    ONCOLOGIST = 'ONCOLOGIST',
    PEDIATRICIAN = 'PEDIATRICIAN',
    PSYCHIATRIST = 'PSYCHIATRIST',
    DERMATOLOGIST = 'DERMATOLOGIST',

    // Allied Health Professionals
    PHYSICAL_THERAPIST = 'PHYSICAL_THERAPIST',
    OCCUPATIONAL_THERAPIST = 'OCCUPATIONAL_THERAPIST',
    SPEECH_LANGUAGE_PATHOLOGIST = 'SPEECH_LANGUAGE_PATHOLOGIST',
    DIETITIAN = 'DIETITIAN',
    RESPIRATORY_THERAPIST = 'RESPIRATORY_THERAPIST',

    // Technical Roles
    RADIOLOGIC_TECHNOLOGIST = 'RADIOLOGIC_TECHNOLOGIST',
    MEDICAL_LABORATORY_TECHNICIAN = 'MEDICAL_LABORATORY_TECHNICIAN',
    PHARMACY_TECHNICIAN = 'PHARMACY_TECHNICIAN',

    // Mental Health Professionals
    PSYCHOLOGIST = 'PSYCHOLOGIST',
    CLINICAL_SOCIAL_WORKER = 'CLINICAL_SOCIAL_WORKER',
    COUNSELOR = 'COUNSELOR',

    // Public Health Roles
    EPIDEMIOLOGIST = 'EPIDEMIOLOGIST',
    PUBLIC_HEALTH_SPECIALIST = 'PUBLIC_HEALTH_SPECIALIST',
    HEALTH_EDUCATOR = 'HEALTH_EDUCATOR',

    // Administrative Roles
    MEDICAL_RECORDS_MANAGER = 'MEDICAL_RECORDS_MANAGER',
    HEALTHCARE_MANAGER = 'HEALTHCARE_MANAGER',
    PATIENT_SERVICES_COORDINATOR = 'PATIENT_SERVICES_COORDINATOR',

    // Research Roles
    CLINICAL_RESEARCH_COORDINATOR = 'CLINICAL_RESEARCH_COORDINATOR',
    BIOMEDICAL_RESEARCHER = 'BIOMEDICAL_RESEARCHER',

    // Emergency Services
    PARAMEDIC = 'PARAMEDIC',
    EMERGENCY_MEDICAL_TECHNICIAN = 'EMERGENCY_MEDICAL_TECHNICIAN',

    // Other
    MEDICAL_ASSISTANT = 'MEDICAL_ASSISTANT',
    CASE_MANAGER = 'CASE_MANAGER',
    HEALTHCARE_CONSULTANT = 'HEALTHCARE_CONSULTANT'
}