export enum NonProfitRoles {
    // Executive Leadership
    EXECUTIVE_DIRECTOR = 'EXECUTIVE_DIRECTOR',
    CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
    PRESIDENT = 'PRESIDENT',
    VICE_PRESIDENT = 'VICE_PRESIDENT',
    CHIEF_OPERATING_OFFICER = 'CHIEF_OPERATING_OFFICER',
    CHIEF_FINANCIAL_OFFICER = 'CHIEF_FINANCIAL_OFFICER',

    // Program Management
    PROGRAM_DIRECTOR = 'PROGRAM_DIRECTOR',
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    PROGRAM_COORDINATOR = 'PROGRAM_COORDINATOR',
    OUTREACH_COORDINATOR = 'OUTREACH_COORDINATOR',

    // Fundraising and Development
    DEVELOPMENT_DIRECTOR = 'DEVELOPMENT_DIRECTOR',
    FUNDRAISING_MANAGER = 'FUNDRAISING_MANAGER',
    GRANT_WRITER = 'GRANT_WRITER',
    DONOR_RELATIONS_MANAGER = 'DONOR_RELATIONS_MANAGER',

    // Communications and Marketing
    COMMUNICATIONS_DIRECTOR = 'COMMUNICATIONS_DIRECTOR',
    MARKETING_MANAGER = 'MARKETING_MANAGER',
    PUBLIC_RELATIONS_SPECIALIST = 'PUBLIC_RELATIONS_SPECIALIST',
    SOCIAL_MEDIA_COORDINATOR = 'SOCIAL_MEDIA_COORDINATOR',
    
    // Human Resources
    HR_DIRECTOR = 'HR_DIRECTOR',
    VOLUNTEER_COORDINATOR = 'VOLUNTEER_COORDINATOR',
    RECRUITMENT_SPECIALIST = 'RECRUITMENT_SPECIALIST',
    
    // Finance and Administration
    FINANCE_MANAGER = 'FINANCE_MANAGER',
    ACCOUNTANT = 'ACCOUNTANT',
    ADMINISTRATIVE_ASSISTANT = 'ADMINISTRATIVE_ASSISTANT',
    OFFICE_MANAGER = 'OFFICE_MANAGER',
    
    // Board of Directors
    BOARD_CHAIR = 'BOARD_CHAIR',
    BOARD_VICE_CHAIR = 'BOARD_VICE_CHAIR',
    BOARD_SECRETARY = 'BOARD_SECRETARY',
    BOARD_TREASURER = 'BOARD_TREASURER',
    BOARD_MEMBER = 'BOARD_MEMBER',
    
    // Program Staff
    CASE_MANAGER = 'CASE_MANAGER',
    SOCIAL_WORKER = 'SOCIAL_WORKER',
    COUNSELOR = 'COUNSELOR',
    RESEARCHER = 'RESEARCHER',
    POLICY_ANALYST = 'POLICY_ANALYST',
    
    // Field Work
    FIELD_COORDINATOR = 'FIELD_COORDINATOR',
    COMMUNITY_ORGANIZER = 'COMMUNITY_ORGANIZER',
    OUTREACH_WORKER = 'OUTREACH_WORKER',
    
    // Technology
    IT_MANAGER = 'IT_MANAGER',
    DATABASE_ADMINISTRATOR = 'DATABASE_ADMINISTRATOR',
    WEBSITE_MANAGER = 'WEBSITE_MANAGER',
    
    // Legal
    LEGAL_COUNSEL = 'LEGAL_COUNSEL',
    COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
    
    // Volunteers
    VOLUNTEER = 'VOLUNTEER',
    INTERN = 'INTERN',
    
    // Advisory Roles
    ADVISOR = 'ADVISOR',
    CONSULTANT = 'CONSULTANT',
    
    // Other
    MEMBER = 'MEMBER',
    SUPPORTER = 'SUPPORTER',
    BENEFICIARY = 'BENEFICIARY',
    
    // Generic
    STAFF = 'STAFF',
    OTHER = 'OTHER'
}