export enum TechnologyIndustryRoles {
    // C-Suite and Executive Roles
    CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
    CHIEF_TECHNOLOGY_OFFICER = 'CHIEF_TECHNOLOGY_OFFICER',
    CHIEF_INFORMATION_OFFICER = 'CHIEF_INFORMATION_OFFICER',
    CHIEF_DATA_OFFICER = 'CHIEF_DATA_OFFICER',
    CHIEF_SECURITY_OFFICER = 'CHIEF_SECURITY_OFFICER',
    CHIEF_PRODUCT_OFFICER = 'CHIEF_PRODUCT_OFFICER',
    VICE_PRESIDENT_OF_ENGINEERING = 'VICE_PRESIDENT_OF_ENGINEERING',

    // Management Roles
    DIRECTOR_OF_ENGINEERING = 'DIRECTOR_OF_ENGINEERING',
    IT_MANAGER = 'IT_MANAGER',
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    PRODUCT_MANAGER = 'PRODUCT_MANAGER',
    SCRUM_MASTER = 'SCRUM_MASTER',

    // Development Roles
    SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
    FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER',
    BACKEND_DEVELOPER = 'BACKEND_DEVELOPER',
    FULL_STACK_DEVELOPER = 'FULL_STACK_DEVELOPER',
    MOBILE_DEVELOPER = 'MOBILE_DEVELOPER',
    DEVOPS_ENGINEER = 'DEVOPS_ENGINEER',
    SITE_RELIABILITY_ENGINEER = 'SITE_RELIABILITY_ENGINEER',

    // Data Roles
    DATA_SCIENTIST = 'DATA_SCIENTIST',
    DATA_ENGINEER = 'DATA_ENGINEER',
    MACHINE_LEARNING_ENGINEER = 'MACHINE_LEARNING_ENGINEER',
    BUSINESS_INTELLIGENCE_ANALYST = 'BUSINESS_INTELLIGENCE_ANALYST',

    // Design Roles
    UX_DESIGNER = 'UX_DESIGNER',
    UI_DESIGNER = 'UI_DESIGNER',
    INTERACTION_DESIGNER = 'INTERACTION_DESIGNER',

    // Security Roles
    INFORMATION_SECURITY_ANALYST = 'INFORMATION_SECURITY_ANALYST',
    CYBERSECURITY_SPECIALIST = 'CYBERSECURITY_SPECIALIST',
    PENETRATION_TESTER = 'PENETRATION_TESTER',

    // Infrastructure Roles
    SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR',
    NETWORK_ENGINEER = 'NETWORK_ENGINEER',
    CLOUD_ARCHITECT = 'CLOUD_ARCHITECT',

    // Quality Assurance Roles
    QUALITY_ASSURANCE_ENGINEER = 'QUALITY_ASSURANCE_ENGINEER',
    TEST_AUTOMATION_ENGINEER = 'TEST_AUTOMATION_ENGINEER',

    // Emerging Tech Roles
    AI_RESEARCHER = 'AI_RESEARCHER',
    BLOCKCHAIN_DEVELOPER = 'BLOCKCHAIN_DEVELOPER',
    IOT_SPECIALIST = 'IOT_SPECIALIST',
    AR_VR_DEVELOPER = 'AR_VR_DEVELOPER',

    // Support Roles
    TECHNICAL_SUPPORT_SPECIALIST = 'TECHNICAL_SUPPORT_SPECIALIST',
    IT_CONSULTANT = 'IT_CONSULTANT',

    // Other
    TECHNICAL_WRITER = 'TECHNICAL_WRITER',
    BUSINESS_ANALYST = 'BUSINESS_ANALYST'
}