// src/constants/metrics.ts

export const METRIC_TYPES = {
  COUNTER: 'counter',
  GAUGE: 'gauge',
  HISTOGRAM: 'histogram',
} as const;

export const DEFAULT_METRICS = {
  API_CALLS: 'API_CALLS',
  ERROR_COUNT: 'ERROR_COUNT',
  REQUEST_COUNT: 'REQUEST_COUNT',
  RESPONSE_TIME: 'RESPONSE_TIME',
  ACTIVE_USERS: 'ACTIVE_USERS',
  LOG_INFO: 'LOG_INFO',
  EMOTION_MAPPING_GET: 'EMOTION_MAPPING_GET',
  EMOTION_MAPPING_CREATE: 'EMOTION_MAPPING_CREATE',
  EMOTION_MAPPING_UPDATE_ALL: 'EMOTION_MAPPING_UPDATE_ALL',
  EMOTION_MAPPING_UPDATE_SINGLE: 'EMOTION_MAPPING_UPDATE_SINGLE',
  EMOTION_MAPPING_UPDATE_FAILED: 'EMOTION_MAPPING_UPDATE_FAILED',
  EMOTION_MAPPING_DELETE: 'EMOTION_MAPPING_DELETE',
  EMOTION_MAPPING_DELETE_FAILED: 'EMOTION_MAPPING_DELETE_FAILED',
  EMOTION_MAPPING_METHOD_NOT_ALLOWED: 'EMOTION_MAPPING_METHOD_NOT_ALLOWED',
  EMOTION_MAPPING_RESPONSE_TIME: 'EMOTION_MAPPING_RESPONSE_TIME',
} as const;

export const METRIC_UNITS = {
  MILLISECONDS: 'ms',
  COUNT: 'count',
  SECONDS: 'seconds',
  BYTES: 'bytes'
} as const;

// Logging constants
export const LOG_LEVELS = {
  ERROR: 'error',
  WARN: 'warn',
  INFO: 'info',
  DEBUG: 'debug',
} as const;

// Environment variables
export const ENV_VARS = {
  NODE_ENV: 'NODE_ENV',
  API_URL: 'API_URL',
  DATABASE_URL: 'DATABASE_URL',
  REDIS_URL: 'REDIS_URL',
} as const;