// PERMISSIONS LIST ARE THE PERMISSION THAT ARE SINGULARLY POSSIBLE FOR ALL USER WHICH
// WE MAPP TOGETHER WITH THE ROLES AND ACCESS LEVEL TO PROVIDE EVEN CLEANER DATA AND SECURITY
export const PERMISSIONS = {
  // User management
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_CHANGE_ROLE: 'USER_CHANGE_ROLE',
  USER_CHANGE_ACCESS_LEVEL: 'USER_CHANGE_ACCESS_LEVEL',

  // Tenant management
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_READ: 'TENANT_READ',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DELETE: 'TENANT_DELETE',

  // Audit log management

AUDIT_ACTIONS: {
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  CREATEUSER: 'CREATEUSER',
  UPDATEUSER: 'UPDATEUSER',
  DELETEUSER: 'DELETEUSER',
  CREATETENANT: 'CREATETENANT',
  UPDATETENANT: 'UPDATETENANT',
  DELETETENANT: 'DELETETENANT',
  CREATEINVOICE: 'CREATEINVOICE',
  UPDATEINVOICE: 'UPDATEINVOICE',
  DELETEINVOICE: 'DELETEINVOICE',
  CREATEPAYMENT: 'CREATEPAYMENT',
  UPDATEPAYMENT: 'UPDATEPAYMENT',
  DELETEPAYMENT: 'DELETEPAYMENT',
  CREATESUBSCRIPTION: 'CREATESUBSCRIPTION',
  UPDATESUBSCRIPTION: 'UPDATESUBSCRIPTION',
  DELETESUBSCRIPTION: 'DELETESUBSCRIPTION',
  CREATERESOURCE: 'CREATERESOURCE',
  UPDATERESOURCE: 'UPDATERESOURCE',
  DELETERESOURCE: 'DELETERESOURCE',
  CREATENOTIFICATION: 'CREATENOTIFICATION',
  UPDATENOTIFICATION: 'UPDATENOTIFICATION',
  DELETENOTIFICATION: 'DELETENOTIFICATION',
  CREATESETTING: 'CREATESETTING',
  UPDATESETTING: 'UPDATESETTING',
  DELETESETTING: 'DELETESETTING',
  CREATEFEATUREFLAG: 'CREATEFEATUREFLAG',
  UPDATEFEATUREFLAG: 'UPDATEFEATUREFLAG',
  DELETEFEATUREFLAG: 'DELETEFEATUREFLAG',
  CREATESTRIPECUSTOMER: 'CREATESTRIPECUSTOMER',
  UPDATESTRIPECUSTOMER: 'UPDATESTRIPECUSTOMER',
  DELETESTRIPECUSTOMER: 'DELETESTRIPECUSTOMER',
  CREATEAUDITTRAIL: 'CREATEAUDITTRAIL',
  UPDATEAUDITTRAIL: 'UPDATEAUDITTRAIL',
  DELETEAUDITTRAIL: 'DELETEAUDITTRAIL',
  CREATESESSION: 'CREATESESSION',
  UPDATESESSION: 'UPDATESESSION',
  DELETESESSION: 'DELETESESSION'
},

  // Resource management
  RESOURCE_CREATE: 'RESOURCE_CREATE',
  RESOURCE_READ: 'RESOURCE_READ',
  RESOURCE_UPDATE: 'RESOURCE_UPDATE',
  RESOURCE_DELETE: 'RESOURCE_DELETE',

  // Storage management
  STORAGE_CREATE: 'STORAGE_CREATE',
  STORAGE_READ: 'STORAGE_READ',
  STORAGE_UPDATE: 'STORAGE_UPDATE',
  STORAGE_DELETE: 'STORAGE_DELETE',

  // Network management
  NETWORK_CREATE: 'NETWORK_CREATE',
  NETWORK_READ: 'NETWORK_READ',
  NETWORK_UPDATE: 'NETWORK_UPDATE',
  NETWORK_DELETE: 'NETWORK_DELETE',

  // Compute management
  COMPUTE_CREATE: 'COMPUTE_CREATE',
  COMPUTE_READ: 'COMPUTE_READ',
  COMPUTE_UPDATE: 'COMPUTE_UPDATE',
  COMPUTE_DELETE: 'COMPUTE_DELETE',

  // Database management
  DATABASE_CREATE: 'DATABASE_CREATE',
  DATABASE_READ: 'DATABASE_READ',
  DATABASE_UPDATE: 'DATABASE_UPDATE',
  DATABASE_DELETE: 'DATABASE_DELETE',

  // Security management
  SECURITY_CREATE: 'SECURITY_CREATE',
  SECURITY_READ: 'SECURITY_READ',
  SECURITY_UPDATE: 'SECURITY_UPDATE',
  SECURITY_DELETE: 'SECURITY_DELETE',

  // Identity management
  IDENTITY_CREATE: 'IDENTITY_CREATE',
  IDENTITY_READ: 'IDENTITY_READ',
  IDENTITY_UPDATE: 'IDENTITY_UPDATE',
  IDENTITY_DELETE: 'IDENTITY_DELETE',

  // AI management
  AI_CREATE: 'AI_CREATE',
  AI_READ: 'AI_READ',
  AI_UPDATE: 'AI_UPDATE',
  AI_DELETE: 'AI_DELETE',

  // Analytics management
  ANALYTICS_CREATE: 'ANALYTICS_CREATE',
  ANALYTICS_READ: 'ANALYTICS_READ',
  ANALYTICS_UPDATE: 'ANALYTICS_UPDATE',
  ANALYTICS_DELETE: 'ANALYTICS_DELETE',

  // IoT management
  IOT_CREATE: 'IOT_CREATE',
  IOT_READ: 'IOT_READ',
  IOT_UPDATE: 'IOT_UPDATE',
  IOT_DELETE: 'IOT_DELETE',

  // DevOps management
  DEVOPS_CREATE: 'DEVOPS_CREATE',
  DEVOPS_READ: 'DEVOPS_READ',
  DEVOPS_UPDATE: 'DEVOPS_UPDATE',
  DEVOPS_DELETE: 'DEVOPS_DELETE',

  // Function management
  FUNCTION_CREATE: 'FUNCTION_CREATE',
  FUNCTION_READ: 'FUNCTION_READ',
  FUNCTION_UPDATE: 'FUNCTION_UPDATE',
  FUNCTION_DELETE: 'FUNCTION_DELETE',

  // Insights management
  INSIGHTS_CREATE: 'INSIGHTS_CREATE',
  INSIGHTS_READ: 'INSIGHTS_READ',
  INSIGHTS_UPDATE: 'INSIGHTS_UPDATE',
  INSIGHTS_DELETE: 'INSIGHTS_DELETE',

  // Billing and Subscription management
  BILLING_VIEW: 'BILLING_VIEW',
  BILLING_UPDATE: 'BILLING_UPDATE',
  SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
  SUBSCRIPTION_UPDATE: 'SUBSCRIPTION_UPDATE',
  SUBSCRIPTION_CANCEL: 'SUBSCRIPTION_CANCEL',
  SUBSCRIPTION_CHANGE: 'SUBSCRIPTION_CHANGE',

  // General management
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',


  // social media management
  FRIEND_REQUEST_SEND: 'FRIEND_REQUEST_SEND',
  FRIEND_REQUEST_ACCEPT: 'FRIEND_REQUEST_ACCEPT',
  FRIEND_LIST_VIEW: 'FRIEND_LIST_VIEW',
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_UPDATE: 'PROFILE_UPDATE',

    // Account type specific permissions
  PERSONAL: {
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    STORAGE_CREATE: 'STORAGE_CREATE',
    STORAGE_READ: 'STORAGE_READ',
    STORAGE_UPDATE: 'STORAGE_UPDATE',
    STORAGE_DELETE: 'STORAGE_DELETE',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    FRIEND_REQUEST_SEND: 'FRIEND_REQUEST_SEND',
    FRIEND_REQUEST_ACCEPT: 'FRIEND_REQUEST_ACCEPT',
    FRIEND_LIST_VIEW: 'FRIEND_LIST_VIEW',
    PROFILE_VIEW: 'PROFILE_VIEW',
    PROFILE_UPDATE: 'PROFILE_UPDATE',
  },

  MEMBER: {
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    STORAGE_CREATE: 'STORAGE_CREATE',
    STORAGE_READ: 'STORAGE_READ',
    STORAGE_UPDATE: 'STORAGE_UPDATE',
    STORAGE_DELETE: 'STORAGE_DELETE',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    FRIEND_REQUEST_SEND: 'FRIEND_REQUEST_SEND',
    FRIEND_REQUEST_ACCEPT: 'FRIEND_REQUEST_ACCEPT',
    FRIEND_LIST_VIEW: 'FRIEND_LIST_VIEW',
    PROFILE_VIEW: 'PROFILE_VIEW',
    PROFILE_UPDATE: 'PROFILE_UPDATE',
  },

  FAMILY: {
    USER_CREATE: 'USER_CREATE',
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',
    STORAGE_CREATE: 'STORAGE_CREATE',
    STORAGE_READ: 'STORAGE_READ',
    STORAGE_UPDATE: 'STORAGE_UPDATE',
    STORAGE_DELETE: 'STORAGE_DELETE',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    FRIEND_REQUEST_SEND: 'FRIEND_REQUEST_SEND',
    FRIEND_REQUEST_ACCEPT: 'FRIEND_REQUEST_ACCEPT',
    FRIEND_LIST_VIEW: 'FRIEND_LIST_VIEW',
    PROFILE_VIEW: 'PROFILE_VIEW',
    PROFILE_UPDATE: 'PROFILE_UPDATE',
  },
  INSTITUTE: {
  // User Management
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_CHANGE_ROLE: 'USER_CHANGE_ROLE',
  USER_CHANGE_ACCESS_LEVEL: 'USER_CHANGE_ACCESS_LEVEL',

  // Resource Management
  RESOURCE_CREATE: 'RESOURCE_CREATE',
  RESOURCE_READ: 'RESOURCE_READ',
  RESOURCE_UPDATE: 'RESOURCE_UPDATE',
  RESOURCE_DELETE: 'RESOURCE_DELETE',

  // Storage Management
  STORAGE_CREATE: 'STORAGE_CREATE',
  STORAGE_READ: 'STORAGE_READ',
  STORAGE_UPDATE: 'STORAGE_UPDATE',
  STORAGE_DELETE: 'STORAGE_DELETE',

  // Database Management
  DATABASE_CREATE: 'DATABASE_CREATE',
  DATABASE_READ: 'DATABASE_READ',
  DATABASE_UPDATE: 'DATABASE_UPDATE',
  DATABASE_DELETE: 'DATABASE_DELETE',

  // Analytics and Settings
  ANALYTICS_CREATE: 'ANALYTICS_CREATE',
  ANALYTICS_READ: 'ANALYTICS_READ',
  ANALYTICS_UPDATE: 'ANALYTICS_UPDATE',
  ANALYTICS_DELETE: 'ANALYTICS_DELETE',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',

  // Billing and Subscription
  BILLING_READ: 'BILLING_READ',
  BILLING_UPDATE: 'BILLING_UPDATE',
  SUBSCRIPTION_READ: 'SUBSCRIPTION_READ',
  SUBSCRIPTION_UPDATE: 'SUBSCRIPTION_UPDATE',
  SUBSCRIPTION_DELETE: 'SUBSCRIPTION_DELETE',

  // Curriculum and Course Management
  CURRICULUM_CREATE: 'CURRICULUM_CREATE',
  CURRICULUM_READ: 'CURRICULUM_READ',
  CURRICULUM_UPDATE: 'CURRICULUM_UPDATE',
  CURRICULUM_DELETE: 'CURRICULUM_DELETE',
  COURSE_CREATE: 'COURSE_CREATE',
  COURSE_READ: 'COURSE_READ',
  COURSE_UPDATE: 'COURSE_UPDATE',
  COURSE_DELETE: 'COURSE_DELETE',
  COURSE_ENROLL: 'COURSE_ENROLL',
  COURSE_UNENROLL: 'COURSE_UNENROLL',

  // Student Management
  STUDENT_RECORD_CREATE: 'STUDENT_RECORD_CREATE',
  STUDENT_RECORD_READ: 'STUDENT_RECORD_READ',
  STUDENT_RECORD_UPDATE: 'STUDENT_RECORD_UPDATE',
  STUDENT_RECORD_DELETE: 'STUDENT_RECORD_DELETE',
  STUDENT_GRADE_CREATE: 'STUDENT_GRADE_CREATE',
  STUDENT_GRADE_READ: 'STUDENT_GRADE_READ',

  // Faculty Management
  FACULTY_RECORD_CREATE: 'FACULTY_RECORD_CREATE',
  FACULTY_RECORD_READ: 'FACULTY_RECORD_READ',
  FACULTY_RECORD_UPDATE: 'FACULTY_RECORD_UPDATE',
  FACULTY_RECORD_DELETE: 'FACULTY_RECORD_DELETE',
  FACULTY_COURSE_ASSIGN: 'FACULTY_COURSE_ASSIGN',

  // Academic Planning
  ACADEMIC_CALENDAR_MANAGE: 'ACADEMIC_CALENDAR_MANAGE',
  PROGRAM_CREATE: 'PROGRAM_CREATE',
  PROGRAM_READ: 'PROGRAM_READ',
  PROGRAM_UPDATE: 'PROGRAM_UPDATE',
  PROGRAM_DELETE: 'PROGRAM_DELETE',

  // Admissions and Enrollment
  ADMISSION_APPLICATION_CREATE: 'ADMISSION_APPLICATION_CREATE',
  ADMISSION_APPLICATION_READ: 'ADMISSION_APPLICATION_READ',
  ADMISSION_APPLICATION_UPDATE: 'ADMISSION_APPLICATION_UPDATE',
  ADMISSION_APPLICATION_DELETE: 'ADMISSION_APPLICATION_DELETE',
  ENROLLMENT_CREATE: 'ENROLLMENT_CREATE',
  ENROLLMENT_READ: 'ENROLLMENT_READ',
  ENROLLMENT_UPDATE: 'ENROLLMENT_UPDATE',
  ENROLLMENT_DELETE: 'ENROLLMENT_DELETE',

  // Financial Aid
  FINANCIAL_AID_CREATE: 'FINANCIAL_AID_CREATE',
  FINANCIAL_AID_READ: 'FINANCIAL_AID_READ',
  FINANCIAL_AID_UPDATE: 'FINANCIAL_AID_UPDATE',
  FINANCIAL_AID_DELETE: 'FINANCIAL_AID_DELETE',
  SCHOLARSHIP_CREATE: 'SCHOLARSHIP_CREATE',
  SCHOLARSHIP_READ: 'SCHOLARSHIP_READ',
  SCHOLARSHIP_UPDATE: 'SCHOLARSHIP_UPDATE',
  SCHOLARSHIP_DELETE: 'SCHOLARSHIP_DELETE',

  // Research Management
  RESEARCH_PROJECT_CREATE: 'RESEARCH_PROJECT_CREATE',
  RESEARCH_PROJECT_READ: 'RESEARCH_PROJECT_READ',
  RESEARCH_PROJECT_UPDATE: 'RESEARCH_PROJECT_UPDATE',
  RESEARCH_PROJECT_DELETE: 'RESEARCH_PROJECT_DELETE',
  GRANT_CREATE: 'GRANT_CREATE',
  GRANT_READ: 'GRANT_READ',
  GRANT_UPDATE: 'GRANT_UPDATE',
  GRANT_DELETE: 'GRANT_DELETE',
  PUBLICATION_CREATE: 'PUBLICATION_CREATE',
  PUBLICATION_READ: 'PUBLICATION_READ',
  PUBLICATION_UPDATE: 'PUBLICATION_UPDATE',
  PUBLICATION_DELETE: 'PUBLICATION_DELETE',

  // Library Management
  LIBRARY_RESOURCE_CREATE: 'LIBRARY_RESOURCE_CREATE',
  LIBRARY_RESOURCE_READ: 'LIBRARY_RESOURCE_READ',
  LIBRARY_RESOURCE_UPDATE: 'LIBRARY_RESOURCE_UPDATE',
  LIBRARY_RESOURCE_DELETE: 'LIBRARY_RESOURCE_DELETE',
  LIBRARY_CIRCULATION_MANAGE: 'LIBRARY_CIRCULATION_MANAGE',

  // Facility Management
  FACILITY_CREATE: 'FACILITY_CREATE',
  FACILITY_READ: 'FACILITY_READ',
  FACILITY_UPDATE: 'FACILITY_UPDATE',
  FACILITY_DELETE: 'FACILITY_DELETE',

  // Event Management
  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_READ: 'EVENT_READ',
  EVENT_UPDATE: 'EVENT_UPDATE',
  EVENT_DELETE: 'EVENT_DELETE',

  // Alumni Relations
  ALUMNI_CREATE: 'ALUMNI_CREATE',
  ALUMNI_READ: 'ALUMNI_READ',
  ALUMNI_UPDATE: 'ALUMNI_UPDATE',
  ALUMNI_DELETE: 'ALUMNI_DELETE',

  // Assessment and Accreditation
  ASSESSMENT_CREATE: 'ASSESSMENT_CREATE',
  ASSESSMENT_READ: 'ASSESSMENT_READ',
  ASSESSMENT_UPDATE: 'ASSESSMENT_UPDATE',
  ASSESSMENT_DELETE: 'ASSESSMENT_DELETE',
  ACCREDITATION_MANAGE: 'ACCREDITATION_MANAGE',

  // Student Services
  STUDENT_SERVICE_CREATE: 'STUDENT_SERVICE_CREATE',
  STUDENT_SERVICE_READ: 'STUDENT_SERVICE_READ',
  STUDENT_SERVICE_UPDATE: 'STUDENT_SERVICE_UPDATE',
  STUDENT_SERVICE_DELETE: 'STUDENT_SERVICE_DELETE',

  // Athletics
  ATHLETIC_PROGRAM_CREATE: 'ATHLETIC_PROGRAM_CREATE',
  ATHLETIC_PROGRAM_READ: 'ATHLETIC_PROGRAM_READ',
  ATHLETIC_PROGRAM_UPDATE: 'ATHLETIC_PROGRAM_UPDATE',
  ATHLETIC_PROGRAM_DELETE: 'ATHLETIC_PROGRAM_DELETE',

  // Technology and LMS
  LMS_MANAGE: 'LMS_MANAGE',
  IT_INFRASTRUCTURE_MANAGE: 'IT_INFRASTRUCTURE_MANAGE',

  // Compliance and Legal
  COMPLIANCE_CREATE: 'COMPLIANCE_CREATE',
  COMPLIANCE_READ: 'COMPLIANCE_READ',
  COMPLIANCE_UPDATE: 'COMPLIANCE_UPDATE',
  COMPLIANCE_DELETE: 'COMPLIANCE_DELETE',
  LEGAL_DOCUMENT_CREATE: 'LEGAL_DOCUMENT_CREATE',
  LEGAL_DOCUMENT_READ: 'LEGAL_DOCUMENT_READ',
  LEGAL_DOCUMENT_UPDATE: 'LEGAL_DOCUMENT_UPDATE',
  LEGAL_DOCUMENT_DELETE: 'LEGAL_DOCUMENT_DELETE',

  // Internationalization
  INTERNATIONAL_PROGRAM_CREATE: 'INTERNATIONAL_PROGRAM_CREATE',
  INTERNATIONAL_PROGRAM_READ: 'INTERNATIONAL_PROGRAM_READ',
  INTERNATIONAL_PROGRAM_UPDATE: 'INTERNATIONAL_PROGRAM_UPDATE',
  INTERNATIONAL_PROGRAM_DELETE: 'INTERNATIONAL_PROGRAM_DELETE',
    INTERNATIONAL_STUDENT_MANAGE: 'INTERNATIONAL_STUDENT_MANAGE',
  
    INTELLECTUAL_PROPERTY_MANAGE: 'INTELLECTUAL_PROPERTY_MANAGE',
    CERTIFICATION_CREATE: 'CERTIFICATION_CREATE',
    CERTIFICATION_READ: 'CERTIFICATION_READ',
    CERTIFICATION_UPDATE: 'CERTIFICATION_UPDATE',
    CERTIFICATION_DELETE: 'CERTIFICATION_DELETE',
    CERTIFICATION_ASSIGN: 'CERTIFICATION_ASSIGN',
    CERTIFICATION_ENROLL: 'CERTIFICATION_ENROLL',
    PARENT_RECORD_MANAGE: 'PARENT_RECORD_MANAGE',
 ANALYTICS_MANAGE: 'ANALYTICS_MANAGE',
    GRANT_MANAGE: 'GRANT_MANAGE',
    FACULTY_RECORD_MANAGE: 'FACULTY_RECORD_MANAGE',
  DATABASE_MANAGE: 'DATABASE_MANAGE',
BILLING_MANAGE: 'BILLING_MANAGE',
SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',
PROGRAM_MANAGE: 'PROGRAM_MANAGE',
ADMISSION_APPLICATION_MANAGE: 'ADMISSION_APPLICATION_MANAGE',
ENROLLMENT_MANAGE: 'ENROLLMENT_MANAGE',
FINANCIAL_AID_MANAGE: 'FINANCIAL_AID_MANAGE',
SCHOLARSHIP_MANAGE: 'SCHOLARSHIP_MANAGE',
ASSESSMENT_MANAGE: 'ASSESSMENT_MANAGE',
COMPLIANCE_MANAGE: 'COMPLIANCE_MANAGE',
LEGAL_DOCUMENT_MANAGE: 'LEGAL_DOCUMENT_MANAGE',
PARENT_PORTAL_ACCESS: 'PARENT_PORTAL_ACCESS',
PARENT_COMMUNICATION_MANAGE: 'PARENT_COMMUNICATION_MANAGE',
GRADE_LEVEL_MANAGE: 'GRADE_LEVEL_MANAGE',
IEP_CREATE: 'IEP_CREATE',
IEP_READ: 'IEP_READ',
IEP_UPDATE: 'IEP_UPDATE',
IEP_DELETE: 'IEP_DELETE',
SPECIALIZED_RESOURCE_CREATE: 'SPECIALIZED_RESOURCE_CREATE',
SPECIALIZED_RESOURCE_READ: 'SPECIALIZED_RESOURCE_READ',
SPECIALIZED_RESOURCE_UPDATE: 'SPECIALIZED_RESOURCE_UPDATE',
SPECIALIZED_RESOURCE_DELETE: 'SPECIALIZED_RESOURCE_DELETE',
SPECIALIZED_RESOURCE_ASSIGN: 'SPECIALIZED_RESOURCE_ASSIGN',
ACCOMMODATION_MANAGE: 'ACCOMMODATION_MANAGE',
VOCATIONAL_PROGRAM_CREATE: 'VOCATIONAL_PROGRAM_CREATE',
VOCATIONAL_PROGRAM_READ: 'VOCATIONAL_PROGRAM_READ',
VOCATIONAL_PROGRAM_UPDATE: 'VOCATIONAL_PROGRAM_UPDATE',
VOCATIONAL_PROGRAM_DELETE: 'VOCATIONAL_PROGRAM_DELETE',
VOCATIONAL_PROGRAM_ENROLL: 'VOCATIONAL_PROGRAM_ENROLL',
INDUSTRY_PARTNERSHIP_CREATE: 'INDUSTRY_PARTNERSHIP_CREATE',
INDUSTRY_PARTNERSHIP_READ: 'INDUSTRY_PARTNERSHIP_READ',
INDUSTRY_PARTNERSHIP_UPDATE: 'INDUSTRY_PARTNERSHIP_UPDATE',
INDUSTRY_PARTNERSHIP_DELETE: 'INDUSTRY_PARTNERSHIP_DELETE',
APPRENTICESHIP_MANAGE: 'APPRENTICESHIP_MANAGE',
WORKFORCE_DEVELOPMENT_MANAGE: 'WORKFORCE_DEVELOPMENT_MANAGE',
CERTIFICATION_PROGRAM_MANAGE: 'CERTIFICATION_PROGRAM_MANAGE',
GRANT_APPLY: 'GRANT_APPLY',
ADVANCED_COURSE_MANAGE: 'ADVANCED_COURSE_MANAGE',
RESEARCH_FUNDING_MANAGE: 'RESEARCH_FUNDING_MANAGE',
CHILD_SAFETY_MANAGE: 'CHILD_SAFETY_MANAGE',
SPECIAL_EDUCATION_PROGRAM_MANAGE: 'SPECIAL_EDUCATION_PROGRAM_MANAGE',
ASSISTIVE_TECHNOLOGY_MANAGE: 'ASSISTIVE_TECHNOLOGY_MANAGE',
INDUSTRY_TREND_ANALYZE: 'INDUSTRY_TREND_ANALYZE',
  },

  BUSINESS: {
    USER_CREATE: 'USER_CREATE',
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',
    USER_CHANGE_ROLE: 'USER_CHANGE_ROLE',
    USER_CHANGE_ACCESS_LEVEL: 'USER_CHANGE_ACCESS_LEVEL',
    TENANT_CREATE: 'TENANT_CREATE',
    TENANT_READ: 'TENANT_READ',
    TENANT_UPDATE: 'TENANT_UPDATE',
    TENANT_DELETE: 'TENANT_DELETE',
    RESOURCE_CREATE: 'RESOURCE_CREATE',
    RESOURCE_READ: 'RESOURCE_READ',
    RESOURCE_UPDATE: 'RESOURCE_UPDATE',
    RESOURCE_DELETE: 'RESOURCE_DELETE',
    STORAGE_CREATE: 'STORAGE_CREATE',
    STORAGE_READ: 'STORAGE_READ',
    STORAGE_UPDATE: 'STORAGE_UPDATE',
    STORAGE_DELETE: 'STORAGE_DELETE',
    NETWORK_CREATE: 'NETWORK_CREATE',
    NETWORK_READ: 'NETWORK_READ',
    NETWORK_UPDATE: 'NETWORK_UPDATE',
    NETWORK_DELETE: 'NETWORK_DELETE',
    COMPUTE_CREATE: 'COMPUTE_CREATE',
    COMPUTE_READ: 'COMPUTE_READ',
    COMPUTE_UPDATE: 'COMPUTE_UPDATE',
    COMPUTE_DELETE: 'COMPUTE_DELETE',
    DATABASE_CREATE: 'DATABASE_CREATE',
    DATABASE_READ: 'DATABASE_READ',
    DATABASE_UPDATE: 'DATABASE_UPDATE',
    DATABASE_DELETE: 'DATABASE_DELETE',
    SECURITY_CREATE: 'SECURITY_CREATE',
    SECURITY_READ: 'SECURITY_READ',
    SECURITY_UPDATE: 'SECURITY_UPDATE',
    SECURITY_DELETE: 'SECURITY_DELETE',
    IDENTITY_CREATE: 'IDENTITY_CREATE',
    IDENTITY_READ: 'IDENTITY_READ',
    IDENTITY_UPDATE: 'IDENTITY_UPDATE',
    IDENTITY_DELETE: 'IDENTITY_DELETE',
    AI_CREATE: 'AI_CREATE',
    AI_READ: 'AI_READ',
    AI_UPDATE: 'AI_UPDATE',
    AI_DELETE: 'AI_DELETE',
    ANALYTICS_CREATE: 'ANALYTICS_CREATE',
    ANALYTICS_READ: 'ANALYTICS_READ',
    ANALYTICS_UPDATE: 'ANALYTICS_UPDATE',
    ANALYTICS_DELETE: 'ANALYTICS_DELETE',
    IOT_CREATE: 'IOT_CREATE',
    IOT_READ: 'IOT_READ',
    IOT_UPDATE: 'IOT_UPDATE',
    IOT_DELETE: 'IOT_DELETE',
    DEVOPS_CREATE: 'DEVOPS_CREATE',
    DEVOPS_READ: 'DEVOPS_READ',
    DEVOPS_UPDATE: 'DEVOPS_UPDATE',
    DEVOPS_DELETE: 'DEVOPS_DELETE',
    FUNCTION_CREATE: 'FUNCTION_CREATE',
    FUNCTION_READ: 'FUNCTION_READ',
    FUNCTION_UPDATE: 'FUNCTION_UPDATE',
    FUNCTION_DELETE: 'FUNCTION_DELETE',
    INSIGHTS_CREATE: 'INSIGHTS_CREATE',
    INSIGHTS_READ: 'INSIGHTS_READ',
    INSIGHTS_UPDATE: 'INSIGHTS_UPDATE',
    INSIGHTS_DELETE: 'INSIGHTS_DELETE',
    BILLING_VIEW: 'BILLING_VIEW',
    BILLING_UPDATE: 'BILLING_UPDATE',
    SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
    SUBSCRIPTION_UPDATE: 'SUBSCRIPTION_UPDATE',
    SUBSCRIPTION_CANCEL: 'SUBSCRIPTION_CANCEL',
    SUBSCRIPTION_CHANGE: 'SUBSCRIPTION_CHANGE',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  },

  FINANCIAL: {
    USER_CREATE: 'USER_CREATE',
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',
    USER_CHANGE_ROLE: 'USER_CHANGE_ROLE',
    USER_CHANGE_ACCESS_LEVEL: 'USER_CHANGE_ACCESS_LEVEL',
    TENANT_CREATE: 'TENANT_CREATE',
    TENANT_READ: 'TENANT_READ',
    TENANT_UPDATE: 'TENANT_UPDATE',
    TENANT_DELETE: 'TENANT_DELETE',
    RESOURCE_CREATE: 'RESOURCE_CREATE',
    RESOURCE_READ: 'RESOURCE_READ',
    RESOURCE_UPDATE: 'RESOURCE_UPDATE',
    RESOURCE_DELETE: 'RESOURCE_DELETE',
    STORAGE_CREATE: 'STORAGE_CREATE',
    STORAGE_READ: 'STORAGE_READ',
    STORAGE_UPDATE: 'STORAGE_UPDATE',
    STORAGE_DELETE: 'STORAGE_DELETE',
    DATABASE_CREATE: 'DATABASE_CREATE',
    DATABASE_READ: 'DATABASE_READ',
    DATABASE_UPDATE: 'DATABASE_UPDATE',
    DATABASE_DELETE: 'DATABASE_DELETE',
    SECURITY_CREATE: 'SECURITY_CREATE',
    SECURITY_READ: 'SECURITY_READ',
    SECURITY_UPDATE: 'SECURITY_UPDATE',
    SECURITY_DELETE: 'SECURITY_DELETE',
    ANALYTICS_CREATE: 'ANALYTICS_CREATE',
    ANALYTICS_READ: 'ANALYTICS_READ',
    ANALYTICS_UPDATE: 'ANALYTICS_UPDATE',
    ANALYTICS_DELETE: 'ANALYTICS_DELETE',
    INSIGHTS_CREATE: 'INSIGHTS_CREATE',
    INSIGHTS_READ: 'INSIGHTS_READ',
    INSIGHTS_UPDATE: 'INSIGHTS_UPDATE',
    INSIGHTS_DELETE: 'INSIGHTS_DELETE',
    BILLING_VIEW: 'BILLING_VIEW',
    BILLING_UPDATE: 'BILLING_UPDATE',
    SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
    SUBSCRIPTION_UPDATE: 'SUBSCRIPTION_UPDATE',
    SUBSCRIPTION_CANCEL: 'SUBSCRIPTION_CANCEL',
    SUBSCRIPTION_CHANGE: 'SUBSCRIPTION_CHANGE',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  },

  NON_PROFIT: {
    USER_CREATE: 'USER_CREATE',
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',
    USER_CHANGE_ROLE: 'USER_CHANGE_ROLE',
    USER_CHANGE_ACCESS_LEVEL: 'USER_CHANGE_ACCESS_LEVEL',
    TENANT_CREATE: 'TENANT_CREATE',
    TENANT_READ: 'TENANT_READ',
    TENANT_UPDATE: 'TENANT_UPDATE',
    TENANT_DELETE: 'TENANT_DELETE',
    RESOURCE_CREATE: 'RESOURCE_CREATE',
    RESOURCE_READ: 'RESOURCE_READ',
    RESOURCE_UPDATE: 'RESOURCE_UPDATE',
    RESOURCE_DELETE: 'RESOURCE_DELETE',
    STORAGE_CREATE: 'STORAGE_CREATE',
    STORAGE_READ: 'STORAGE_READ',
    STORAGE_UPDATE: 'STORAGE_UPDATE',
    STORAGE_DELETE: 'STORAGE_DELETE',
    DATABASE_CREATE: 'DATABASE_CREATE',
    DATABASE_READ: 'DATABASE_READ',
    DATABASE_UPDATE: 'DATABASE_UPDATE',
    DATABASE_DELETE: 'DATABASE_DELETE',
    ANALYTICS_CREATE: 'ANALYTICS_CREATE',
    ANALYTICS_READ: 'ANALYTICS_READ',
    ANALYTICS_UPDATE: 'ANALYTICS_UPDATE',
    ANALYTICS_DELETE: 'ANALYTICS_DELETE',
    INSIGHTS_CREATE: 'INSIGHTS_CREATE',
    INSIGHTS_READ: 'INSIGHTS_READ',
    INSIGHTS_UPDATE: 'INSIGHTS_UPDATE',
    INSIGHTS_DELETE: 'INSIGHTS_DELETE',
    BILLING_VIEW: 'BILLING_VIEW',
    BILLING_UPDATE: 'BILLING_UPDATE',
    SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
    SUBSCRIPTION_UPDATE: 'SUBSCRIPTION_UPDATE',
    SUBSCRIPTION_CANCEL: 'SUBSCRIPTION_CANCEL',
    SUBSCRIPTION_CHANGE: 'SUBSCRIPTION_CHANGE',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  },

    HEALTH_CARE: {
    // User management
    USER_CREATE: 'USER_CREATE',
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',
    USER_CHANGE_ROLE: 'USER_CHANGE_ROLE',
    USER_CHANGE_ACCESS_LEVEL: 'USER_CHANGE_ACCESS_LEVEL',

    // Tenant management
    TENANT_CREATE: 'TENANT_CREATE',
    TENANT_READ: 'TENANT_READ',
    TENANT_UPDATE: 'TENANT_UPDATE',
    TENANT_DELETE: 'TENANT_DELETE',

    // Resource management
    RESOURCE_CREATE: 'RESOURCE_CREATE',
    RESOURCE_READ: 'RESOURCE_READ',
    RESOURCE_UPDATE: 'RESOURCE_UPDATE',
    RESOURCE_DELETE: 'RESOURCE_DELETE',

    // Storage management (for medical records, images, etc.)
    STORAGE_CREATE: 'STORAGE_CREATE',
    STORAGE_READ: 'STORAGE_READ',
    STORAGE_UPDATE: 'STORAGE_UPDATE',
    STORAGE_DELETE: 'STORAGE_DELETE',

    // Database management (for patient records, medical history)
    DATABASE_CREATE: 'DATABASE_CREATE',
    DATABASE_READ: 'DATABASE_READ',
    DATABASE_UPDATE: 'DATABASE_UPDATE',
    DATABASE_DELETE: 'DATABASE_DELETE',

    // Security management (crucial for healthcare data)
    SECURITY_CREATE: 'SECURITY_CREATE',
    SECURITY_READ: 'SECURITY_READ',
    SECURITY_UPDATE: 'SECURITY_UPDATE',
    SECURITY_DELETE: 'SECURITY_DELETE',

    // Analytics management (for medical research, trends)
    ANALYTICS_CREATE: 'ANALYTICS_CREATE',
    ANALYTICS_READ: 'ANALYTICS_READ',
    ANALYTICS_UPDATE: 'ANALYTICS_UPDATE',
    ANALYTICS_DELETE: 'ANALYTICS_DELETE',

    // Billing and Subscription management
    BILLING_VIEW: 'BILLING_VIEW',
    BILLING_UPDATE: 'BILLING_UPDATE',
    SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
    SUBSCRIPTION_UPDATE: 'SUBSCRIPTION_UPDATE',
    SUBSCRIPTION_CANCEL: 'SUBSCRIPTION_CANCEL',
    SUBSCRIPTION_CHANGE: 'SUBSCRIPTION_CHANGE',

    // General management
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    ANALYTICS_VIEW: 'ANALYTICS_VIEW',

    // Healthcare-specific permissions
    PATIENT_RECORD_CREATE: 'PATIENT_RECORD_CREATE',
    PATIENT_RECORD_READ: 'PATIENT_RECORD_READ',
    PATIENT_RECORD_UPDATE: 'PATIENT_RECORD_UPDATE',
    PATIENT_RECORD_DELETE: 'PATIENT_RECORD_DELETE',
    
    MEDICAL_HISTORY_VIEW: 'MEDICAL_HISTORY_VIEW',
    MEDICAL_HISTORY_UPDATE: 'MEDICAL_HISTORY_UPDATE',
    
    PRESCRIPTION_CREATE: 'PRESCRIPTION_CREATE',
    PRESCRIPTION_READ: 'PRESCRIPTION_READ',
    PRESCRIPTION_UPDATE: 'PRESCRIPTION_UPDATE',
    PRESCRIPTION_DELETE: 'PRESCRIPTION_DELETE',
    
    LAB_RESULT_CREATE: 'LAB_RESULT_CREATE',
    LAB_RESULT_READ: 'LAB_RESULT_READ',
    LAB_RESULT_UPDATE: 'LAB_RESULT_UPDATE',
    LAB_RESULT_DELETE: 'LAB_RESULT_DELETE',
    
    APPOINTMENT_SCHEDULE: 'APPOINTMENT_SCHEDULE',
    APPOINTMENT_VIEW: 'APPOINTMENT_VIEW',
    APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
    APPOINTMENT_CANCEL: 'APPOINTMENT_CANCEL',
    
    INSURANCE_CLAIM_CREATE: 'INSURANCE_CLAIM_CREATE',
    INSURANCE_CLAIM_READ: 'INSURANCE_CLAIM_READ',
    INSURANCE_CLAIM_UPDATE: 'INSURANCE_CLAIM_UPDATE',
    INSURANCE_CLAIM_DELETE: 'INSURANCE_CLAIM_DELETE',
    
    AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
    
    TELEMEDICINE_SESSION_CREATE: 'TELEMEDICINE_SESSION_CREATE',
    TELEMEDICINE_SESSION_JOIN: 'TELEMEDICINE_SESSION_JOIN',
    
    MEDICAL_DEVICE_INTEGRATE: 'MEDICAL_DEVICE_INTEGRATE',
    MEDICAL_DEVICE_READ: 'MEDICAL_DEVICE_READ',
    
    RESEARCH_DATA_ACCESS: 'RESEARCH_DATA_ACCESS',
    ANONYMIZED_DATA_EXPORT: 'ANONYMIZED_DATA_EXPORT',
  },
  
} as const;

export type Permissions = keyof typeof PERMISSIONS;

