
export enum AlternativeEducationRoles {
    // Alternative Education
    HOMESCHOOL_COORDINATOR = 'HOMESCHOOL_COORDINATOR',
    TUTORING_SPECIALIST = 'TUTORING_SPECIALIST',
    ALTERNATIVE_EDUCATION_FACILITATOR = 'ALTERNATIVE_EDUCATION_FACILITATOR',
    EXPERIENTIAL_LEARNING_COORDINATOR = 'EXPERIENTIAL_LEARNING_COORDINATOR',

}