export enum HigherEducationRoles {
    // Executive Leadership
    PRESIDENT = 'PRESIDENT',
    CHANCELLOR = 'CHANCELLOR',
    VICE_CHANCELLOR = 'VICE_CHANCELLOR',
    PROVOST = 'PROVOST',
    VICE_PRESIDENT = 'VICE_PRESIDENT',
    CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
    EXECUTIVE_DIRECTOR = 'EXECUTIVE_DIRECTOR',

    // Academic Leadership
    DEAN = 'DEAN',
    ASSOCIATE_DEAN = 'ASSOCIATE_DEAN',
    DEPARTMENT_CHAIR = 'DEPARTMENT_CHAIR',
    PROGRAM_DIRECTOR = 'PROGRAM_DIRECTOR',

    // Administrative Leadership
    CHIEF_FINANCIAL_OFFICER = 'CHIEF_FINANCIAL_OFFICER',
    CHIEF_OPERATIONS_OFFICER = 'CHIEF_OPERATIONS_OFFICER',
    CHIEF_INFORMATION_OFFICER = 'CHIEF_INFORMATION_OFFICER',
    REGISTRAR = 'REGISTRAR',
    BURSAR = 'BURSAR',
    ADMISSIONS_DIRECTOR = 'ADMISSIONS_DIRECTOR',

    // Faculty Positions
    PROFESSOR = 'PROFESSOR',
    ASSOCIATE_PROFESSOR = 'ASSOCIATE_PROFESSOR',
    ASSISTANT_PROFESSOR = 'ASSISTANT_PROFESSOR',
    ADJUNCT_PROFESSOR = 'ADJUNCT_PROFESSOR',
    LECTURER = 'LECTURER',
    INSTRUCTOR = 'INSTRUCTOR',
    RESEARCH_PROFESSOR = 'RESEARCH_PROFESSOR',
    VISITING_PROFESSOR = 'VISITING_PROFESSOR',

    // Research Positions
    RESEARCH_DIRECTOR = 'RESEARCH_DIRECTOR',
    PRINCIPAL_INVESTIGATOR = 'PRINCIPAL_INVESTIGATOR',
    SENIOR_RESEARCHER = 'SENIOR_RESEARCHER',
    RESEARCHER = 'RESEARCHER',
    POSTDOCTORAL_RESEARCHER = 'POSTDOCTORAL_RESEARCHER',
    RESEARCH_ASSISTANT = 'RESEARCH_ASSISTANT',

    // Student Support
    ACADEMIC_ADVISOR = 'ACADEMIC_ADVISOR',
    CAREER_COUNSELOR = 'CAREER_COUNSELOR',
    STUDENT_AFFAIRS_DIRECTOR = 'STUDENT_AFFAIRS_DIRECTOR',
    FINANCIAL_AID_OFFICER = 'FINANCIAL_AID_OFFICER',
    RESIDENCE_LIFE_DIRECTOR = 'RESIDENCE_LIFE_DIRECTOR',

    // Library and Information Services
    LIBRARIAN = 'LIBRARIAN',
    ARCHIVIST = 'ARCHIVIST',
    CURATOR = 'CURATOR',
    INFORMATION_TECHNOLOGY_SPECIALIST = 'INFORMATION_TECHNOLOGY_SPECIALIST',

    // Facilities and Operations
    FACILITIES_MANAGER = 'FACILITIES_MANAGER',
    CAMPUS_SECURITY_CHIEF = 'CAMPUS_SECURITY_CHIEF',
    SUSTAINABILITY_COORDINATOR = 'SUSTAINABILITY_COORDINATOR',

    // Development and External Relations
    DEVELOPMENT_DIRECTOR = 'DEVELOPMENT_DIRECTOR',
    ALUMNI_RELATIONS_MANAGER = 'ALUMNI_RELATIONS_MANAGER',
    PUBLIC_RELATIONS_MANAGER = 'PUBLIC_RELATIONS_MANAGER',
    GRANT_WRITER = 'GRANT_WRITER',

    // Athletics (for institutions with sports programs)
    ATHLETIC_DIRECTOR = 'ATHLETIC_DIRECTOR',
    HEAD_COACH = 'HEAD_COACH',
    ASSISTANT_COACH = 'ASSISTANT_COACH',

    // Health and Wellness
    HEALTH_SERVICES_DIRECTOR = 'HEALTH_SERVICES_DIRECTOR',
    COUNSELING_SERVICES_DIRECTOR = 'COUNSELING_SERVICES_DIRECTOR',
    WELLNESS_PROGRAM_COORDINATOR = 'WELLNESS_PROGRAM_COORDINATOR',

    // Specialized Roles
    DIVERSITY_AND_INCLUSION_OFFICER = 'DIVERSITY_AND_INCLUSION_OFFICER',
    INTERNATIONAL_PROGRAMS_DIRECTOR = 'INTERNATIONAL_PROGRAMS_DIRECTOR',
    CONTINUING_EDUCATION_DIRECTOR = 'CONTINUING_EDUCATION_DIRECTOR',
    TECHNOLOGY_TRANSFER_OFFICER = 'TECHNOLOGY_TRANSFER_OFFICER',
    INSTITUTIONAL_RESEARCH_DIRECTOR = 'INSTITUTIONAL_RESEARCH_DIRECTOR',

    // Support Staff
    ADMINISTRATIVE_ASSISTANT = 'ADMINISTRATIVE_ASSISTANT',
    OFFICE_MANAGER = 'OFFICE_MANAGER',
    LAB_TECHNICIAN = 'LAB_TECHNICIAN',
    TEACHING_ASSISTANT = 'TEACHING_ASSISTANT',

    // Other
    BOARD_MEMBER = 'BOARD_MEMBER',
    TRUSTEE = 'TRUSTEE',
    CONSULTANT = 'CONSULTANT',

    // Generic
    OTHER = 'OTHER'
}