export enum K_12_Roles {

    // K-12 and Elementary Specific Roles
    SUPERINTENDENT = 'SUPERINTENDENT',
    ASSISTANT_SUPERINTENDENT = 'ASSISTANT_SUPERINTENDENT',
    PRINCIPAL = 'PRINCIPAL',
    VICE_PRINCIPAL = 'VICE_PRINCIPAL',
    TEACHER = 'TEACHER',
    ELEMENTARY_TEACHER = 'ELEMENTARY_TEACHER',
    MIDDLE_SCHOOL_TEACHER = 'MIDDLE_SCHOOL_TEACHER',
    HIGH_SCHOOL_TEACHER = 'HIGH_SCHOOL_TEACHER',
    SPECIAL_EDUCATION_TEACHER = 'SPECIAL_EDUCATION_TEACHER',
    SCHOOL_COUNSELOR = 'SCHOOL_COUNSELOR',
    SCHOOL_PSYCHOLOGIST = 'SCHOOL_PSYCHOLOGIST',
    CURRICULUM_COORDINATOR = 'CURRICULUM_COORDINATOR',
    INSTRUCTIONAL_COACH = 'INSTRUCTIONAL_COACH',
    READING_SPECIALIST = 'READING_SPECIALIST',
    MATH_SPECIALIST = 'MATH_SPECIALIST',
    ENGLISH_AS_SECOND_LANGUAGE_TEACHER = 'ENGLISH_AS_SECOND_LANGUAGE_TEACHER',
    GIFTED_AND_TALENTED_COORDINATOR = 'GIFTED_AND_TALENTED_COORDINATOR',
    SCHOOL_NURSE = 'SCHOOL_NURSE',
    SCHOOL_SOCIAL_WORKER = 'SCHOOL_SOCIAL_WORKER',
    SCHOOL_RESOURCE_OFFICER = 'SCHOOL_RESOURCE_OFFICER',
    TRANSPORTATION_DIRECTOR = 'TRANSPORTATION_DIRECTOR',
    FOOD_SERVICE_DIRECTOR = 'FOOD_SERVICE_DIRECTOR',
    PARAPROFESSIONAL = 'PARAPROFESSIONAL',
    SCHOOL_SECRETARY = 'SCHOOL_SECRETARY',

    // Update existing roles to be more inclusive
    FACULTY_MEMBER = 'FACULTY_MEMBER', // More general than PROFESSOR
    EDUCATOR = 'EDUCATOR', // Can apply to both K-12 and higher education

    // Generic
    OTHER = 'OTHER'
}