    
export enum ProfessionalTrainingEducationRoles {
    // Professional Education
    POLICE_ACADEMY_GRADUATE = 'POLICE_ACADEMY_GRADUATE',
    FIRE_ACADEMY_GRADUATE = 'FIRE_ACADEMY_GRADUATE',
    MILITARY_TACTICS_GRADUATE = 'MILITARY_TACTICS_GRADUATE',
    FLIGHT_SCHOOL_GRADUATE = 'FLIGHT_SCHOOL_GRADUATE',
    CULINARY_ARTS_SCHOOL_GRADUATE = 'CULINARY_ARTS_SCHOOL_GRADUATE',
}