   

export enum ResearchInstitutesRoles {
    // Research Institutes
    RESEARCH_FELLOW = 'RESEARCH_FELLOW',
    POLICY_ANALYST = 'POLICY_ANALYST',
    THINK_TANK_DIRECTOR = 'THINK_TANK_DIRECTOR',
    SCIENTIFIC_RESEARCHER = 'SCIENTIFIC_RESEARCHER',
    SOCIAL_SCIENTIST = 'SOCIAL_SCIENTIST',
}