
export enum SpecialEducationRoles {
    // Special Education
    SPECIAL_EDUCATION_COORDINATOR = 'SPECIAL_EDUCATION_COORDINATOR',
    BEHAVIOR_INTERVENTION_SPECIALIST = 'BEHAVIOR_INTERVENTION_SPECIALIST',
    GIFTED_EDUCATION_SPECIALIST = 'GIFTED_EDUCATION_SPECIALIST',
    INDIVIDUALIZED_EDUCATION_PROGRAM_COORDINATOR = 'INDIVIDUALIZED_EDUCATION_PROGRAM_COORDINATOR',
}