

export enum VocationalAndAdultEducationRoles {

    // Vocational and Adult Education
    VOCATIONAL_INSTRUCTOR = 'VOCATIONAL_INSTRUCTOR',
    TRADE_SKILLS_INSTRUCTOR = 'TRADE_SKILLS_INSTRUCTOR',
    ADULT_EDUCATION_COORDINATOR = 'ADULT_EDUCATION_COORDINATOR',
    CONTINUING_EDUCATION_SPECIALIST = 'CONTINUING_EDUCATION_SPECIALIST',
    LANGUAGE_INSTRUCTOR = 'LANGUAGE_INSTRUCTOR',
    WORKFORCE_DEVELOPMENT_SPECIALIST = 'WORKFORCE_DEVELOPMENT_SPECIALIST',
}