import { PERMISSIONS } from '../permissions';

export type BusinessPermission = typeof PERMISSIONS.BUSINESS[keyof typeof PERMISSIONS.BUSINESS];

export const L0_PERMISSIONS: BusinessPermission[] = [
  PERMISSIONS.BUSINESS.USER_READ,
  PERMISSIONS.BUSINESS.RESOURCE_READ,
  PERMISSIONS.BUSINESS.STORAGE_READ,
  PERMISSIONS.BUSINESS.NETWORK_READ,
  PERMISSIONS.BUSINESS.COMPUTE_READ,
  PERMISSIONS.BUSINESS.DATABASE_READ,
];

export const L1_PERMISSIONS: BusinessPermission[] = [
  PERMISSIONS.BUSINESS.USER_CREATE,
  PERMISSIONS.BUSINESS.USER_UPDATE,
  PERMISSIONS.BUSINESS.RESOURCE_CREATE,
  PERMISSIONS.BUSINESS.RESOURCE_UPDATE,
  PERMISSIONS.BUSINESS.STORAGE_CREATE,
  PERMISSIONS.BUSINESS.STORAGE_UPDATE,
  PERMISSIONS.BUSINESS.NETWORK_CREATE,
  PERMISSIONS.BUSINESS.NETWORK_UPDATE,
  PERMISSIONS.BUSINESS.COMPUTE_CREATE,
  PERMISSIONS.BUSINESS.COMPUTE_UPDATE,
  PERMISSIONS.BUSINESS.DATABASE_CREATE,
  PERMISSIONS.BUSINESS.DATABASE_UPDATE,
];

export const L2_PERMISSIONS: BusinessPermission[] = [
  PERMISSIONS.BUSINESS.USER_DELETE,
  PERMISSIONS.BUSINESS.RESOURCE_DELETE,
  PERMISSIONS.BUSINESS.STORAGE_DELETE,
  PERMISSIONS.BUSINESS.NETWORK_DELETE,
  PERMISSIONS.BUSINESS.COMPUTE_DELETE,
  PERMISSIONS.BUSINESS.DATABASE_DELETE,
  PERMISSIONS.BUSINESS.SECURITY_READ,
  PERMISSIONS.BUSINESS.IDENTITY_READ,
  PERMISSIONS.BUSINESS.AI_READ,
  PERMISSIONS.BUSINESS.ANALYTICS_READ,
  PERMISSIONS.BUSINESS.IOT_READ,
  PERMISSIONS.BUSINESS.DEVOPS_READ,
  PERMISSIONS.BUSINESS.FUNCTION_READ,
  PERMISSIONS.BUSINESS.INSIGHTS_READ,
];

export const L3_PERMISSIONS: BusinessPermission[] = [
  PERMISSIONS.BUSINESS.USER_CHANGE_ROLE,
  PERMISSIONS.BUSINESS.SECURITY_CREATE,
  PERMISSIONS.BUSINESS.SECURITY_UPDATE,
  PERMISSIONS.BUSINESS.IDENTITY_CREATE,
  PERMISSIONS.BUSINESS.IDENTITY_UPDATE,
  PERMISSIONS.BUSINESS.AI_CREATE,
  PERMISSIONS.BUSINESS.AI_UPDATE,
  PERMISSIONS.BUSINESS.ANALYTICS_CREATE,
  PERMISSIONS.BUSINESS.ANALYTICS_UPDATE,
  PERMISSIONS.BUSINESS.IOT_CREATE,
  PERMISSIONS.BUSINESS.IOT_UPDATE,
  PERMISSIONS.BUSINESS.DEVOPS_CREATE,
  PERMISSIONS.BUSINESS.DEVOPS_UPDATE,
  PERMISSIONS.BUSINESS.FUNCTION_CREATE,
  PERMISSIONS.BUSINESS.FUNCTION_UPDATE,
  PERMISSIONS.BUSINESS.INSIGHTS_CREATE,
  PERMISSIONS.BUSINESS.INSIGHTS_UPDATE,
  PERMISSIONS.BUSINESS.BILLING_VIEW,
  PERMISSIONS.BUSINESS.SUBSCRIPTION_VIEW,
];

export const L4_PERMISSIONS: BusinessPermission[] = [
  PERMISSIONS.BUSINESS.USER_CHANGE_ACCESS_LEVEL,
  PERMISSIONS.BUSINESS.TENANT_CREATE,
  PERMISSIONS.BUSINESS.TENANT_READ,
  PERMISSIONS.BUSINESS.TENANT_UPDATE,
  PERMISSIONS.BUSINESS.TENANT_DELETE,
  PERMISSIONS.BUSINESS.SECURITY_DELETE,
  PERMISSIONS.BUSINESS.IDENTITY_DELETE,
  PERMISSIONS.BUSINESS.AI_DELETE,
  PERMISSIONS.BUSINESS.ANALYTICS_DELETE,
  PERMISSIONS.BUSINESS.IOT_DELETE,
  PERMISSIONS.BUSINESS.DEVOPS_DELETE,
  PERMISSIONS.BUSINESS.FUNCTION_DELETE,
  PERMISSIONS.BUSINESS.INSIGHTS_DELETE,
  PERMISSIONS.BUSINESS.BILLING_UPDATE,
  PERMISSIONS.BUSINESS.SUBSCRIPTION_UPDATE,
  PERMISSIONS.BUSINESS.SUBSCRIPTION_CANCEL,
  PERMISSIONS.BUSINESS.SUBSCRIPTION_CHANGE,
  PERMISSIONS.BUSINESS.SETTINGS_MANAGE,
  PERMISSIONS.BUSINESS.ANALYTICS_VIEW,
];

export const BUSINESS_PERMISSIONS: Record<string, BusinessPermission[]> = {
  L0: L0_PERMISSIONS,
  L1: [...L0_PERMISSIONS, ...L1_PERMISSIONS],
  L2: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS],
  L3: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS],
  L4: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS, ...L4_PERMISSIONS],
};