import { PERMISSIONS } from '../permissions';

export type FamilyPermission = typeof PERMISSIONS.FAMILY[keyof typeof PERMISSIONS.FAMILY];

export const L0_PERMISSIONS: FamilyPermission[] = [
  PERMISSIONS.FAMILY.USER_READ,
  PERMISSIONS.FAMILY.STORAGE_READ,
  PERMISSIONS.FAMILY.FRIEND_LIST_VIEW,
  PERMISSIONS.FAMILY.PROFILE_VIEW,
];

export const L1_PERMISSIONS: FamilyPermission[] = [
  PERMISSIONS.FAMILY.USER_UPDATE,
  PERMISSIONS.FAMILY.STORAGE_CREATE,
  PERMISSIONS.FAMILY.STORAGE_UPDATE,
  PERMISSIONS.FAMILY.FRIEND_REQUEST_SEND,
  PERMISSIONS.FAMILY.FRIEND_REQUEST_ACCEPT,
  PERMISSIONS.FAMILY.PROFILE_UPDATE,
];

export const L2_PERMISSIONS: FamilyPermission[] = [
  PERMISSIONS.FAMILY.STORAGE_DELETE,
  PERMISSIONS.FAMILY.USER_CREATE,
];

export const L3_PERMISSIONS: FamilyPermission[] = [
  PERMISSIONS.FAMILY.SETTINGS_MANAGE,
  PERMISSIONS.FAMILY.USER_DELETE,
];

export const L4_PERMISSIONS: FamilyPermission[] = [];

export const FAMILY_PERMISSIONS: Record<string, FamilyPermission[]> = {
  L0: L0_PERMISSIONS,
  L1: [...L0_PERMISSIONS, ...L1_PERMISSIONS],
  L2: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS],
  L3: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS],
  L4: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS, ...L4_PERMISSIONS],
};