import { PERMISSIONS } from '../permissions';

export type FinancialPermission = typeof PERMISSIONS.FINANCIAL[keyof typeof PERMISSIONS.FINANCIAL];

export const L0_PERMISSIONS: FinancialPermission[] = [
  PERMISSIONS.FINANCIAL.USER_READ,
  PERMISSIONS.FINANCIAL.RESOURCE_READ,
  PERMISSIONS.FINANCIAL.STORAGE_READ,
  PERMISSIONS.FINANCIAL.DATABASE_READ,
];

export const L1_PERMISSIONS: FinancialPermission[] = [
  PERMISSIONS.FINANCIAL.USER_CREATE,
  PERMISSIONS.FINANCIAL.USER_UPDATE,
  PERMISSIONS.FINANCIAL.RESOURCE_CREATE,
  PERMISSIONS.FINANCIAL.RESOURCE_UPDATE,
  PERMISSIONS.FINANCIAL.STORAGE_CREATE,
  PERMISSIONS.FINANCIAL.STORAGE_UPDATE,
  PERMISSIONS.FINANCIAL.DATABASE_CREATE,
  PERMISSIONS.FINANCIAL.DATABASE_UPDATE,
];

export const L2_PERMISSIONS: FinancialPermission[] = [
  PERMISSIONS.FINANCIAL.USER_DELETE,
  PERMISSIONS.FINANCIAL.RESOURCE_DELETE,
  PERMISSIONS.FINANCIAL.STORAGE_DELETE,
  PERMISSIONS.FINANCIAL.DATABASE_DELETE,
  PERMISSIONS.FINANCIAL.SECURITY_READ,
  PERMISSIONS.FINANCIAL.ANALYTICS_READ,
  PERMISSIONS.FINANCIAL.INSIGHTS_READ,
];

export const L3_PERMISSIONS: FinancialPermission[] = [
  PERMISSIONS.FINANCIAL.USER_CHANGE_ROLE,
  PERMISSIONS.FINANCIAL.SECURITY_CREATE,
  PERMISSIONS.FINANCIAL.SECURITY_UPDATE,
  PERMISSIONS.FINANCIAL.ANALYTICS_CREATE,
  PERMISSIONS.FINANCIAL.ANALYTICS_UPDATE,
  PERMISSIONS.FINANCIAL.INSIGHTS_CREATE,
  PERMISSIONS.FINANCIAL.INSIGHTS_UPDATE,
  PERMISSIONS.FINANCIAL.BILLING_VIEW,
  PERMISSIONS.FINANCIAL.SUBSCRIPTION_VIEW,
];

export const L4_PERMISSIONS: FinancialPermission[] = [
  PERMISSIONS.FINANCIAL.USER_CHANGE_ACCESS_LEVEL,
  PERMISSIONS.FINANCIAL.TENANT_CREATE,
  PERMISSIONS.FINANCIAL.TENANT_READ,
  PERMISSIONS.FINANCIAL.TENANT_UPDATE,
  PERMISSIONS.FINANCIAL.TENANT_DELETE,
  PERMISSIONS.FINANCIAL.SECURITY_DELETE,
  PERMISSIONS.FINANCIAL.ANALYTICS_DELETE,
  PERMISSIONS.FINANCIAL.INSIGHTS_DELETE,
  PERMISSIONS.FINANCIAL.BILLING_UPDATE,
  PERMISSIONS.FINANCIAL.SUBSCRIPTION_UPDATE,
  PERMISSIONS.FINANCIAL.SUBSCRIPTION_CANCEL,
  PERMISSIONS.FINANCIAL.SUBSCRIPTION_CHANGE,
  PERMISSIONS.FINANCIAL.SETTINGS_MANAGE,
  PERMISSIONS.FINANCIAL.ANALYTICS_VIEW,
];

export const FINANCIAL_PERMISSIONS: Record<string, FinancialPermission[]> = {
  L0: L0_PERMISSIONS,
  L1: [...L0_PERMISSIONS, ...L1_PERMISSIONS],
  L2: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS],
  L3: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS],
  L4: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS, ...L4_PERMISSIONS],
};