import { PERMISSIONS } from '../permissions';

export type HealthCarePermission = typeof PERMISSIONS.HEALTH_CARE[keyof typeof PERMISSIONS.HEALTH_CARE];

// Define permission levels separately
export const L0_PERMISSIONS: HealthCarePermission[] = [
  PERMISSIONS.HEALTH_CARE.PATIENT_RECORD_READ,
  PERMISSIONS.HEALTH_CARE.MEDICAL_HISTORY_VIEW,
  PERMISSIONS.HEALTH_CARE.APPOINTMENT_VIEW,
  PERMISSIONS.HEALTH_CARE.APPOINTMENT_SCHEDULE,
  PERMISSIONS.HEALTH_CARE.TELEMEDICINE_SESSION_JOIN,
];

export const L1_PERMISSIONS: HealthCarePermission[] = [
  PERMISSIONS.HEALTH_CARE.USER_READ,
  PERMISSIONS.HEALTH_CARE.PATIENT_RECORD_CREATE,
  PERMISSIONS.HEALTH_CARE.PATIENT_RECORD_UPDATE,
  PERMISSIONS.HEALTH_CARE.LAB_RESULT_READ,
  PERMISSIONS.HEALTH_CARE.PRESCRIPTION_READ,
  PERMISSIONS.HEALTH_CARE.APPOINTMENT_UPDATE,
  PERMISSIONS.HEALTH_CARE.APPOINTMENT_CANCEL,
  PERMISSIONS.HEALTH_CARE.INSURANCE_CLAIM_READ,
];

export const L2_PERMISSIONS: HealthCarePermission[] = [
  PERMISSIONS.HEALTH_CARE.MEDICAL_HISTORY_UPDATE,
  PERMISSIONS.HEALTH_CARE.PRESCRIPTION_CREATE,
  PERMISSIONS.HEALTH_CARE.PRESCRIPTION_UPDATE,
  PERMISSIONS.HEALTH_CARE.LAB_RESULT_CREATE,
  PERMISSIONS.HEALTH_CARE.LAB_RESULT_UPDATE,
  PERMISSIONS.HEALTH_CARE.INSURANCE_CLAIM_CREATE,
  PERMISSIONS.HEALTH_CARE.INSURANCE_CLAIM_UPDATE,
  PERMISSIONS.HEALTH_CARE.TELEMEDICINE_SESSION_CREATE,
  PERMISSIONS.HEALTH_CARE.MEDICAL_DEVICE_READ,
];

export const L3_PERMISSIONS: HealthCarePermission[] = [
  PERMISSIONS.HEALTH_CARE.USER_CREATE,
  PERMISSIONS.HEALTH_CARE.USER_UPDATE,
  PERMISSIONS.HEALTH_CARE.RESOURCE_CREATE,
  PERMISSIONS.HEALTH_CARE.RESOURCE_READ,
  PERMISSIONS.HEALTH_CARE.RESOURCE_UPDATE,
  PERMISSIONS.HEALTH_CARE.STORAGE_CREATE,
  PERMISSIONS.HEALTH_CARE.STORAGE_READ,
  PERMISSIONS.HEALTH_CARE.STORAGE_UPDATE,
  PERMISSIONS.HEALTH_CARE.DATABASE_READ,
  PERMISSIONS.HEALTH_CARE.ANALYTICS_READ,
  PERMISSIONS.HEALTH_CARE.BILLING_VIEW,
  PERMISSIONS.HEALTH_CARE.SUBSCRIPTION_VIEW,
  PERMISSIONS.HEALTH_CARE.AUDIT_LOG_VIEW,
  PERMISSIONS.HEALTH_CARE.RESEARCH_DATA_ACCESS,
];

export const L4_PERMISSIONS: HealthCarePermission[] = [
  PERMISSIONS.HEALTH_CARE.USER_DELETE,
  PERMISSIONS.HEALTH_CARE.USER_CHANGE_ROLE,
  PERMISSIONS.HEALTH_CARE.USER_CHANGE_ACCESS_LEVEL,
  PERMISSIONS.HEALTH_CARE.TENANT_CREATE,
  PERMISSIONS.HEALTH_CARE.TENANT_READ,
  PERMISSIONS.HEALTH_CARE.TENANT_UPDATE,
  PERMISSIONS.HEALTH_CARE.TENANT_DELETE,
  PERMISSIONS.HEALTH_CARE.RESOURCE_DELETE,
  PERMISSIONS.HEALTH_CARE.STORAGE_DELETE,
  PERMISSIONS.HEALTH_CARE.DATABASE_CREATE,
  PERMISSIONS.HEALTH_CARE.DATABASE_UPDATE,
  PERMISSIONS.HEALTH_CARE.DATABASE_DELETE,
  PERMISSIONS.HEALTH_CARE.SECURITY_CREATE,
  PERMISSIONS.HEALTH_CARE.SECURITY_READ,
  PERMISSIONS.HEALTH_CARE.SECURITY_UPDATE,
  PERMISSIONS.HEALTH_CARE.SECURITY_DELETE,
  PERMISSIONS.HEALTH_CARE.ANALYTICS_CREATE,
  PERMISSIONS.HEALTH_CARE.ANALYTICS_UPDATE,
  PERMISSIONS.HEALTH_CARE.ANALYTICS_DELETE,
  PERMISSIONS.HEALTH_CARE.BILLING_UPDATE,
  PERMISSIONS.HEALTH_CARE.SUBSCRIPTION_UPDATE,
  PERMISSIONS.HEALTH_CARE.SUBSCRIPTION_CANCEL,
  PERMISSIONS.HEALTH_CARE.SUBSCRIPTION_CHANGE,
  PERMISSIONS.HEALTH_CARE.SETTINGS_MANAGE,
  PERMISSIONS.HEALTH_CARE.ANALYTICS_VIEW,
  PERMISSIONS.HEALTH_CARE.PATIENT_RECORD_DELETE,
  PERMISSIONS.HEALTH_CARE.PRESCRIPTION_DELETE,
  PERMISSIONS.HEALTH_CARE.LAB_RESULT_DELETE,
  PERMISSIONS.HEALTH_CARE.INSURANCE_CLAIM_DELETE,
  PERMISSIONS.HEALTH_CARE.MEDICAL_DEVICE_INTEGRATE,
  PERMISSIONS.HEALTH_CARE.ANONYMIZED_DATA_EXPORT,
];

// ONLY ON YOU REALLY NEED IS THIS SO EXPORT THIS THE ABOVE NOT NECESSARy
// Now create the cumulative permissions
export const HEALTH_CARE_PERMISSIONS: Record<string, HealthCarePermission[]> = {
  L0: L0_PERMISSIONS,
  L1: [...L0_PERMISSIONS, ...L1_PERMISSIONS],
  L2: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS],
  L3: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS],
  L4: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS, ...L4_PERMISSIONS],
};



