import { PERMISSIONS } from '../permissions';

export type NonProfitPermission = typeof PERMISSIONS.NON_PROFIT[keyof typeof PERMISSIONS.NON_PROFIT];

export const L0_PERMISSIONS: NonProfitPermission[] = [
  PERMISSIONS.NON_PROFIT.USER_READ,
  PERMISSIONS.NON_PROFIT.RESOURCE_READ,
  PERMISSIONS.NON_PROFIT.STORAGE_READ,
  PERMISSIONS.NON_PROFIT.DATABASE_READ,
];

export const L1_PERMISSIONS: NonProfitPermission[] = [
  PERMISSIONS.NON_PROFIT.USER_CREATE,
  PERMISSIONS.NON_PROFIT.USER_UPDATE,
  PERMISSIONS.NON_PROFIT.RESOURCE_CREATE,
  PERMISSIONS.NON_PROFIT.RESOURCE_UPDATE,
  PERMISSIONS.NON_PROFIT.STORAGE_CREATE,
  PERMISSIONS.NON_PROFIT.STORAGE_UPDATE,
  PERMISSIONS.NON_PROFIT.DATABASE_CREATE,
  PERMISSIONS.NON_PROFIT.DATABASE_UPDATE,
];

export const L2_PERMISSIONS: NonProfitPermission[] = [
  PERMISSIONS.NON_PROFIT.USER_DELETE,
  PERMISSIONS.NON_PROFIT.RESOURCE_DELETE,
  PERMISSIONS.NON_PROFIT.STORAGE_DELETE,
  PERMISSIONS.NON_PROFIT.DATABASE_DELETE,
  PERMISSIONS.NON_PROFIT.ANALYTICS_READ,
  PERMISSIONS.NON_PROFIT.INSIGHTS_READ,
];

export const L3_PERMISSIONS: NonProfitPermission[] = [
  PERMISSIONS.NON_PROFIT.USER_CHANGE_ROLE,
  PERMISSIONS.NON_PROFIT.ANALYTICS_CREATE,
  PERMISSIONS.NON_PROFIT.ANALYTICS_UPDATE,
  PERMISSIONS.NON_PROFIT.INSIGHTS_CREATE,
  PERMISSIONS.NON_PROFIT.INSIGHTS_UPDATE,
  PERMISSIONS.NON_PROFIT.BILLING_VIEW,
  PERMISSIONS.NON_PROFIT.SUBSCRIPTION_VIEW,
];

export const L4_PERMISSIONS: NonProfitPermission[] = [
  PERMISSIONS.NON_PROFIT.USER_CHANGE_ACCESS_LEVEL,
  PERMISSIONS.NON_PROFIT.TENANT_CREATE,
  PERMISSIONS.NON_PROFIT.TENANT_READ,
  PERMISSIONS.NON_PROFIT.TENANT_UPDATE,
  PERMISSIONS.NON_PROFIT.TENANT_DELETE,
  PERMISSIONS.NON_PROFIT.ANALYTICS_DELETE,
  PERMISSIONS.NON_PROFIT.INSIGHTS_DELETE,
  PERMISSIONS.NON_PROFIT.BILLING_UPDATE,
  PERMISSIONS.NON_PROFIT.SUBSCRIPTION_UPDATE,
  PERMISSIONS.NON_PROFIT.SUBSCRIPTION_CANCEL,
  PERMISSIONS.NON_PROFIT.SUBSCRIPTION_CHANGE,
  PERMISSIONS.NON_PROFIT.SETTINGS_MANAGE,
  PERMISSIONS.NON_PROFIT.ANALYTICS_VIEW,
];

export const NON_PROFIT_PERMISSIONS: Record<string, NonProfitPermission[]> = {
  L0: L0_PERMISSIONS,
  L1: [...L0_PERMISSIONS, ...L1_PERMISSIONS],
  L2: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS],
  L3: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS],
  L4: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS, ...L4_PERMISSIONS],
};