import { PERMISSIONS } from '../permissions';

export type PersonalPermission = typeof PERMISSIONS.PERSONAL[keyof typeof PERMISSIONS.PERSONAL];

export const L0_PERMISSIONS: PersonalPermission[] = [
  PERMISSIONS.PERSONAL.USER_READ,
  PERMISSIONS.PERSONAL.STORAGE_READ,
  PERMISSIONS.PERSONAL.FRIEND_LIST_VIEW,
  PERMISSIONS.PERSONAL.PROFILE_VIEW,
];

export const L1_PERMISSIONS: PersonalPermission[] = [
  PERMISSIONS.PERSONAL.USER_UPDATE,
  PERMISSIONS.PERSONAL.STORAGE_CREATE,
  PERMISSIONS.PERSONAL.STORAGE_UPDATE,
  PERMISSIONS.PERSONAL.FRIEND_REQUEST_SEND,
  PERMISSIONS.PERSONAL.FRIEND_REQUEST_ACCEPT,
  PERMISSIONS.PERSONAL.PROFILE_UPDATE,
];

export const L2_PERMISSIONS: PersonalPermission[] = [
  PERMISSIONS.PERSONAL.STORAGE_DELETE,
];

export const L3_PERMISSIONS: PersonalPermission[] = [
  PERMISSIONS.PERSONAL.SETTINGS_MANAGE,
];

export const L4_PERMISSIONS: PersonalPermission[] = [];

export const PERSONAL_PERMISSIONS: Record<string, PersonalPermission[]> = {
  L0: L0_PERMISSIONS,
  L1: [...L0_PERMISSIONS, ...L1_PERMISSIONS],
  L2: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS],
  L3: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS],
  L4: [...L0_PERMISSIONS, ...L1_PERMISSIONS, ...L2_PERMISSIONS, ...L3_PERMISSIONS, ...L4_PERMISSIONS],
};